export type Teacher = {
  id: string;
  firstName: string;
  lastName: string;
  fatherName: string;
  gender: "male" | "female" | string;
  birthdate: string;
  seriaNo: string;
  finCode: string;
  citizenship: string;
  family: string;
  social: string;
  socialStatus: string;
  userName: string;
  militaryStatus: "var" | "yoxdur";
  disabilityStatus: "var" | "yoxdur" ;
  status?: "var" | "yoxdur" ;
  address: string;
  registerAddress: string;
  tel: string;
  internalTel: string;
  email: string;
  startTime: string;
  totalHour: number;
  department: string;
  academicDegree: string;
  academicName: string;
  stateUnit: { value: string; label: string }[];
  languages:  { value: string; label: string }[];
  languageSkills:  { value: string; label: string }[];
  subjects: string[];
};
