export type Teacher = {
  id: string;
  firstName: string;
  lastName: string;
  fatherName: string;
  gender: "male" | "female" | string;
  birthdate: string;
  seriaNo: string;
  finCode: string;
  citizenship: string;
  family: string;
  social: string;
  socialStatus: string;
  userName: string;
  militaryStatus: "true" | "false" | boolean;
  disabilityStatus: "true" | "false" | boolean;
  status?: "true" | "false" | boolean;
  address: string;
  registerAddress: string;
  tel: string;
  internalTel: string;
  email: string;
  startTime: string;
  totalHour: number;
  department: string;
  academicDegree: string;
  academicName: string;
  stateUnit: string;
  languages: string;
  languageSkills: string;
  subjects: string[];
};
